import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>The Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className="text-center text-3xl font-custom font-bold">
          Work in Progress:) hello..
        </h1>
        <Image
          src="/hello-dog.svg"
          alt="A corgi gently sleeping"
          width={354}
          height={209}
        />

        <p className="font-black">
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
